import path from 'path';
import fs from 'fs/promises';
import child from 'child_process';
import proc from 'process';

const projectItems = [
    'builder',
    'dropper',
    'radithor',
    'runner',
    'shared'
];

const findDirFromItems = async (items) => {
    let current = path.resolve(process.cwd());

    while (true) {
        const matches = await Promise.all(items.map(async (item) => {
            return fs.access(path.join(current, item))
                .then(() => true)
                .catch(() => false)
        }));

        if (matches.every(Boolean)) {
            return current;
        }

        const parent = path.dirname(current);
        if (parent === current) return null;

        current = parent;
    }
};

const runCommand = async (program, args, options) => {
    return new Promise((resolve, reject) => {
        const spawned = child.spawn(program, args, {
            ...options,
            stdio: 'inherit'
        });

        spawned.on('error', reject);

        spawned.on('close', (code, signal) => {
            if (code === 0) {
                resolve();
                return;
            }

            reject(new Error(`Error code ${code}${signal ? `, Signal ${signal}` : ''}`))
        });
    });
};

const project = {};
project.root = await findDirFromItems(projectItems);
project.live = path.join(project.root, '.live') || await fs.mkdir(path.join(project.root, '.live'), {
    recursive: true
});

projectItems.forEach((item) => {
    project[item] = path.join(project.root, item);
});

// builder website

await runCommand('bunx', [
    'esbuild',
    path.join(project.builder, 'public', 'js', 'main.js'),
    '--bundle',
    '--format=esm',
    '--minify',
    '--outfile=' + path.join(project.live, 'builderscript.js.tmp')
]).catch((err) => {
    console.error('failed to bundle builder site js -', err);
    proc.exit(1);
});

await runCommand('bunx', [
    'esbuild',
    path.join(project.builder, 'public', 'style.css'),
    '--bundle',
    '--format=esm',
    '--minify',
    '--outfile=' + path.join(project.live, 'builderstyle.css.tmp')
]).catch((err) => {
    console.error('failed to bundle builder site css -', err);
    proc.exit(1);
});

const builderHtml = await fs.readFile(path.join(
    project.builder,
    'public',
    'index.html'
));

const builderStyle = await fs.readFile(path.join(project.live, 'builderstyle.css.tmp'));
const builderJs = await fs.readFile(path.join(project.live, 'builderscript.js.tmp'));
const builderLayout = await fs.readFile(path.join(project.builder, 'public', 'layout.json'));

const newBuilderHtml = builderHtml
    .toString('utf-8')
    .replace('/* LIVE_BUILDER_CSS */', builderStyle.toString('utf-8'))
    .replace('// LIVE_BUILDER_JS', builderJs.toString('utf-8'))
    // the minification makes the single quotes double
    // inside builder/public/js/site.js
    .replace('"LIVE_BUILDER_SITE_LAYOUT"', JSON.stringify(JSON.parse(builderLayout.toString('utf-8'))));

await fs.writeFile(path.join(project.live, 'builder.html'), newBuilderHtml, 'utf-8').catch((err) => {
    console.error('failed to write builder site file -', err);
    proc.exit(1);
});

await fs.unlink(path.join(project.live, 'builderstyle.css.tmp'));
await fs.unlink(path.join(project.live, 'builderscript.js.tmp'));

// builder backend

await runCommand('go', [
    'build',
    '-o', path.join(project.live, 'builder.exe'),
    '-trimpath',
    '-buildvcs=false',
    '-ldflags=-s -w -buildid=',
    path.join(project.builder, 'main.go')
], {
    cwd: project.builder
}).catch((err) => {
    console.error('failed to build builder server -', err);
    proc.exit(1);
});

// radithor config

const flagBlobIndexes = {};
const configs = [];

// regexps generated by GPT-5.6 Luna
const flagBobIndexesPattern = /\bconst\s*\(\s*\/\/[^\n]*LIVE_BUILDER_FLAG_BLOB_INDEXES[^\n]*\n([\s\S]*?)\)/g;
const uint8Pattern = /^\s*([A-Z_][A-Z_]*)\s+uint8\s*=\s*(\d+)\s*$/gm;
const byteArrayPattern = /((?:\bvar\s*(?:\(\s*)?)?[A-Za-z_]\w*\s*=\s*\[(\d+)\]byte\s*\{\s*)([\s\S]*?)(\s*\})/g;
const configNamePattern = /([A-Za-z]\w*)\s*=\s*\[/
const configByteArrayPattern = /0[x][0-9A-F]{1,2}/g

const radithorConfigPath = path.join(project.radithor, 'store', 'config', 'buildtime.go');
const radithorConfig = await fs.readFile(radithorConfigPath, 'utf-8');

[...radithorConfig.matchAll(flagBobIndexesPattern)].forEach((match) => {
    const blob = match[1];

    [...blob.matchAll(uint8Pattern)].forEach((variable) => {
        const name = variable[1];
        const value = variable[2];

        flagBlobIndexes[name] = Number.parseInt(value, 10);
    });
});

const updatedConfig = radithorConfig.replace(byteArrayPattern, (match, prefix, length, body, end) => {
    const nameMatch = prefix.match(configNamePattern);
    if (!nameMatch) return match;

    const name = nameMatch[1];
    const theLength = Number(length);

    const bytes = body.match(configByteArrayPattern);
    if (bytes.length < 8) return match;

    const fingerprint = new Uint8Array(8);
    crypto.getRandomValues(fingerprint);

    const newBytes = Array.from(fingerprint, (byte) => {
        return `0x${byte.toString(16).padStart(2, '0').toUpperCase()}`;
    });

    let updated = 0;

    const updateBody = body.replace(configByteArrayPattern, (oldByte) => {
        if (updated >= 8) {
            return oldByte;
        }

        return newBytes[updated++];
    });

    configs.push({
        name: name,
        length: theLength,
        fingerprint: Array.from(fingerprint)
    });

    return prefix + updateBody + end;
});

await fs.writeFile(radithorConfigPath, updatedConfig, 'utf-8').catch((err) => {
    console.error('failed to write builder site file -', err);
    proc.exit(1);
});

await fs.writeFile(path.join(project.live, 'radithor.json'), JSON.stringify({
    indexes: flagBlobIndexes,
    configs: configs
}), 'utf-8').catch((err) => {
    console.error('failed to write builder site file -', err);
    proc.exit(1);
});

// radithor

await runCommand('go', [
    'build',
    '-o', path.join(project.live, 'radithor.bin'),
    '-trimpath',
    '-buildvcs=false',
    '-ldflags=-s -w -buildid=',
    path.join(project.radithor, 'main.go')
], {
    cwd: project.radithor
}).catch((err) => {
    console.error('failed to build radithor -', err);
    proc.exit(1);
});
